//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlankTypeCharacteristic
    {
        public int Id { get; set; }
        public Nullable<int> BalnkTypeId { get; set; }
        public Nullable<int> CharacterId { get; set; }
        public Nullable<int> DiseaseId { get; set; }
    
        public virtual BlankType BlankType { get; set; }
        public virtual Characterisitcs Characterisitcs { get; set; }
        public virtual Diseases Diseases { get; set; }
    }
}
