//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blank
    {
        public Blank()
        {
            this.CurrentCharacteristicsValue = new HashSet<CurrentCharacteristicsValue>();
            this.CurrentDiseaseValue = new HashSet<CurrentDiseaseValue>();
        }
    
        public int Id { get; set; }
        public string CreateDate { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Person_Id { get; set; }
    
        public virtual BlankType BlankType { get; set; }
        public virtual ICollection<CurrentCharacteristicsValue> CurrentCharacteristicsValue { get; set; }
        public virtual ICollection<CurrentDiseaseValue> CurrentDiseaseValue { get; set; }
        public virtual Person Person { get; set; }
    }
}
