//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlankTypeCharacteristic
    {
        public int Id { get; set; }
        public Nullable<int> BalnkTypeId { get; set; }
        public Nullable<int> CharacterId { get; set; }
        public Nullable<int> DiseaseId { get; set; }
    
        public virtual BlankType BlankType { get; set; }
        public virtual Characterisitcs Characterisitcs { get; set; }
        public virtual Diseases Diseases { get; set; }
    }
}
