//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blank
    {
        public Blank()
        {
            this.CurrentCharacteristicsValue = new HashSet<CurrentCharacteristicsValue>();
            this.CurrentDiseaseValue = new HashSet<CurrentDiseaseValue>();
        }
    
        public int Id { get; set; }
        public string CreateDate { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Person_Id { get; set; }
    
        public virtual BlankType BlankType { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<CurrentCharacteristicsValue> CurrentCharacteristicsValue { get; set; }
        public virtual ICollection<CurrentDiseaseValue> CurrentDiseaseValue { get; set; }
    }
}
