//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlankType
    {
        public BlankType()
        {
            this.Blank = new HashSet<Blank>();
            this.BlankTypeCharacteristic = new HashSet<BlankTypeCharacteristic>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Blank> Blank { get; set; }
        public virtual ICollection<BlankTypeCharacteristic> BlankTypeCharacteristic { get; set; }
    }
}
