//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characterisitcs
    {
        public Characterisitcs()
        {
            this.BlankTypeCharacteristic = new HashSet<BlankTypeCharacteristic>();
            this.CharacteristicsValue = new HashSet<CharacteristicsValue>();
            this.CurrentCharacteristicsValue = new HashSet<CurrentCharacteristicsValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }    
        public virtual ICollection<BlankTypeCharacteristic> BlankTypeCharacteristic { get; set; }
        public virtual ICollection<CharacteristicsValue> CharacteristicsValue { get; set; }
        public virtual ICollection<CurrentCharacteristicsValue> CurrentCharacteristicsValue { get; set; }
    }
}
