//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characterisitcs
    {
        public Characterisitcs()
        {
            this.BlankTypeCharacteristic = new HashSet<BlankTypeCharacteristic>();
            this.CharacteristicsValue = new HashSet<CharacteristicsValue>();
            this.CurrentCharacteristicsValue = new HashSet<CurrentCharacteristicsValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BlankTypeCharacteristic> BlankTypeCharacteristic { get; set; }
        public virtual ICollection<CharacteristicsValue> CharacteristicsValue { get; set; }
        public virtual ICollection<CurrentCharacteristicsValue> CurrentCharacteristicsValue { get; set; }
    }
}
