//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentCharacteristicsValue
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<int> BlankId { get; set; }
        public Nullable<int> CharId { get; set; }
    
        public virtual Blank Blank { get; set; }
        public virtual Characterisitcs Characterisitcs { get; set; }
    }
}
