//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_First_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diseases
    {
        public Diseases()
        {
            this.BlankTypeCharacteristic = new HashSet<BlankTypeCharacteristic>();
            this.CurrentDiseaseValue = new HashSet<CurrentDiseaseValue>();
            this.DiseasesValue = new HashSet<DiseasesValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BlankTypeCharacteristic> BlankTypeCharacteristic { get; set; }
        public virtual ICollection<CurrentDiseaseValue> CurrentDiseaseValue { get; set; }
        public virtual ICollection<DiseasesValue> DiseasesValue { get; set; }
    }
}
